version: '2'

services:

  app:
    build: .
    container_name: emirna-frontend
    ports:
      - 8080:8080

  nginx:
    image: nginx:alpine
    container_name: emirna-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 8080
    depends_on:
      - app